include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - packages/*

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    sort_constructors_first: false