name: subsocial_auth_example
description: Flutter example showing how to user subsocial_auth

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  subsocial_auth:
    path: ./packages/subsocial_auth/
  subsocial_sdk:
    path: ./packages/subsocial_auth/packages/subsocial_sdk/
  flex_color_scheme: ^3.0.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11
  go_router: ^2.1.1
  collection: ^1.15.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
